ips:
  - "172.18.5-18,50-69,43-44,84-86,100,128,160.*"
  - "172.19.8-10.*"
  - "172.20.1.*"
port: ""
thread: ""
password: ""

skips:
  - '总'
  - 'huiyishi'
  - '会议室'
  - '信息'

ssids:
  cover:
    - id: score2@github.com
      password: 17308930
      encryption: WPA2_PSK2
      frequency: WLAN_2G
      hide: false
      vlan: 0
    - id: score2@github.com
      password: 17308930
      encryption: WPA2_PSK2
      frequency: WLAN_5G
      hide: false
      vlan: 0
  # 删除永远优先于添加
  # 根据 ssid 名字匹配
  remove:
    - "228"